### ISSUE TITLE
Need note explaining build required for designer.

### ISSUE THREAD

**Issue by docfresh** [iceteagroup/Wisej-3-Beta#16]
I installed the beta into VS2019; templates were not there so I ran the Developer Command Prompt to update things as instructed, then they appeared.  However, the WiseJ3 template does not load the designer until you build the project.  The "View Designer" option is missing from context menu in Window1.cs code until then. I believe this is standard .NET 5/6 Winforms behavior.  Please add a note saying you must build for designer to work.

**Comment by dezren39** [comment]
You may want to try the beta using VS2022, I don't know if there is a difference but I do know that 2022 is supported in 3.

**Comment by lucapivato** [comment]
You have to build because of nuget packages. That the standard VS behavior.
