### ISSUE TITLE
Designer .NET 4.8

### ISSUE THREAD

**Issue by DirkBozza** [iceteagroup/Wisej-3-Beta#17]
In an NET6 Projekt I can´t use multiple Targets with .NET4.8 for the designer. As example I have an EntitiyFrameworkCore project for NET6 include, so I can´t compile it with multiple targets, so the designer is not working... any ideas?

**Comment by AlaaTrAce** [comment]
Hi @DirkBozza ,

I just tried installing EFCore 6 on a fresh Wisej3 project, and I didn't get any compilation errors or designer problems.
In general, packages that require a specific .NET version will only be targeted by that version, which is the case for example for EFCore.
So in that case, when you use the designer, you shouldn't get an error.

Can you please provide us with more details, maybe a screenshot of the error, or if possible a small test project?

Thank you,
Alaa

**Comment by DirkBozza** [comment]
Ok, with a simple project doing nothing it works, if you don´t call any function in these packages. If you call any function you must include specific nuget versions for the net versions 6 and 4.8. You must manually change/install all used nuget packages with the correct net version to compile it.
If you have a complex library to include, it will be hard work to manually change/install all nuget packages only to use the designer.
For example EntityFrameworkCore for net6 use Version 6.0.1 and for net4.8 you must use Version 3.1.22 to compile it.
If the code is the same for net6 and net48 you can do it, but if it is incompatible that can´t be the solution to change all code lines with #if/#else to compile it only for the designer. The only reason to do all that things is the net 4.8 designer. Is there a net6 designer planed in near future?

**Comment by DirkBozza** [comment]
![grafik](https://user-images.githubusercontent.com/52238298/147703211-88d9d2ca-3860-4d08-9522-a382f3a20f25.png)

**Comment by larsontim12** [comment]
@DirkBozza See this thread: https://github.com/iceteagroup/Wisej-3-Beta/issues/12#issuecomment-991173454
