### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by dezren39** [iceteagroup/Wisej-3-Beta#18]
Is there an example project of a wisej-2 project with a branch/pr of the upgrade to wisej-3? Even like, a simple hello world form in wisej-2 with a branch showing the commits upgrading to wisej-3, a minimum viable concept of the upgrade? Maybe there is and I'm missing it.

**Comment by dezren39** [comment]
Ideally a cross-platform wisej-3 hello world that also includes a Dockerfile? :-)

**Comment by LRufenacht** [comment]
Hi Drewry,

There is no example migration with version history, but the things to consider are:
* New SDK Project Format
* LaunchSettings.json
* Startup.cs
* and more...

Full list here: https://docs.wisej.com/wisej-3-beta/getting-started/upgrade-existing-projects.

Assuming you used the Wisej 3 installer, you can find the cross-platform HelloWorld project under \Documents\Wisej 3.0\Projects.

HTH,
Levie
