### ISSUE TITLE
Events not firing inside DataRepeater using .net6.0

### ISSUE THREAD

**Issue by AKWahlmann** [iceteagroup/Wisej-3-Beta#27]
I have a LinkLabel inside the DataRepeater and want to execute an event when it is clicked. This works as expected when the target framework is set to net48 but the event is not fired when it is set to net6.0.

**Comment by FrankITG** [comment]
Hi,
sorry for the late reply. We´ll check on our end and get back to you.

Best regards
Frank

**Comment by FrankITG** [comment]
We could reproduce and will work on a fix.
We´ll inform you when an updated Wisej version is available.

Best regards
Frank
